language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm run clean && npm install
env:
  global:
    secure: E2rHDs3NgoAaaVb01kJijmow3c+GMSFxBUDoRtlASOAYA+a52FpWtLHHILTusO8tlT8PfhmwZejWnLIC1xvnHGed+vHvi5N52zF6naZkJKFtne3JS+RNi6C10Hk6M7/pjVGvUI8gPZz9MfsmjmN1hV+vdiB3lVG1s7jS0fre/rZnAZLpIynZNOuCAg3PrEe02GdgJAwhOdkPfn8+InntLpeu5Ep80/6pZB3uN/nPtxndBpkBbf9hWCB6kNCm5DMdNyZPFQIeMOtS782Vs1DTT1qQvuHh+EFYFZYyGrs6enzd336GKFqdCy1zpcax5J49FoAmeb4sG5yOze6j8ow2C/anjpRqo0txRJYIGf9gjv301QkInPj33gpk+38JOeR+1oCfJDbfDvy+gc0WrDliLVm/DKwvaVatWuvwsAphi/nY4X5H7FWF4HYzU5dh7QcEMfoMslGzJQP2QD93BkWAnNZZXaM5N/tnpryl0mHXIqQXf+0IOUxN9QVQTr4OAOkxK0B5z8Xe9xrIwBLF098i6HgO08jJvc3rrLBYN4Tp5yQnyqd+gyAIY//C80dgr0bpzhm5ikDU3BIxKAQc9s/9PKReXP5uDd3LD7cJAEH3ADCzhilQYsMQ6T+4l344AoUeVSKZ7Mw6ZK0J21Iwb1xzrrZfbVaOvQM0V7zRtIrrkdI=
script: npm run build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: docroot
  on:
    branch: dev
  edge: true