language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm run clean && npm install
env:
  global:
    secure: GY8OzVSc/HLM+63wsw08tIC2iQom5Xnvwtc/aT5OPoYXFLJetixm5uI76yTkJn0LEAOKxWZrz0wwODzNdy8l6N76SlGXbgagmX8JBnpdL88eohnTFM7FzpdCiZ40NpTrW2kJ2WoYF47aX56O1c9Qh84lf+7gYiOBiIH2c6Cr5R6e6COZUzlpErVsyFZj52Nu2wVuDNiWYX711WTqqPP0QXXu8epc9SAdBRacTZ2xpF6D6fhW4t42X7oSFV5InhTdWH25XfVOrMmNH1nhVdmO7dQqES/SQTI3RXXMTcJwE3qX7BD2w2N3WVLp5cglD+VZ+0wpNSBnk/nlw/3Mk0RRgHkJS2Zx/H5cjUaeul6zLlsZQXr8WFYhsKnuR6kQhGHUMOw6khZrnhq63+7WKEhXQscZ8G4/2qL4PtaiVTvmnYCJ3KrijQUD23sCojs1gPOGNU2XQ3wSZ5/JI8swLUtb0saJhGAKKsrY4celcrdPb2o7T69oKp5zriRUdhTkw2nidRi0PF6CKOgiC9aJT/t9igKPHiUpLB/rlnd5pow9DTfqlhox62gx01+S8b4y7b70/1M7OMlUrcb/2k5EWotjTrlQr31EdX7nTvxPxoRGPewIQ6ISCIfkCI/CM52XOgDqMNI1JIqRdUerSAVNjdpv5cWldBtwFNSHOd4XbzgO5kY=
    - OoMVRSEwpEHCSJbkdeVI6l86kBkknM1e0v5stMqNnNAGBJSGDVri6I9XWQTIwXd2yOitLDFiIcjW5fYicwAu6qdAJADMm2eJBPmLav//B0rK0oUJAJ2svMTR/gEts1IXrDFRs5hgNVJ8r9VYz4zaNQe6nkmS6EM+GoRozMEy2YK7ZQCqx6r463kV3qkZMvcdxGgzwgE2Pyka2rVjJILkNWgSxIlBSSOYd/GxVv9EpXdZLIP7oOcKGtbNhyujNX/5FK5i+RLhr3vzlLBSuVB1jz6nXVvzu0cpmny05Puy0+uEI/HKFedn1GMRX/k7a9BOPz4TpkrRTYxtw0pq52lr9jAOVsYW32mNB37FlsuMVGoIRFCHbUnsRkwHizPCBUcBLApxMao3zP7NtmJ9g1U7nITtB63Aoc7jgk9L4ZV9Hd5qFo6lT0u9E0mut9vABr5+8L4z7gvsYadhAykoGzVW4W17OCTTZP0nuYMaAA4qXADaYNlj8Dqhcc2vB7aKj9nkMBFlWwFaach8Ak+xhyQrjL19SW1xRRZjp9Iwl9cquU/zUZ5TcRiM59vp2x7OX/te4M7XFQ5jIOBgjeqhSK2yEB9nskgZgoTXpkW5sivoJT8nv9e3Sc3Gjjrvw7xxclC3pEWKTItB+KxihHLYqKD09ItHikHJRDXIZmrNKdlqt4M=
script: npm run build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: docroot
  on:
    branch: dev
  edge: true